services:
  postgres-heal-order-hub:
    image: postgres:alpine3.17
    hostname: postgres
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: heal-order-hub
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - heal-order-hub-data:/data/postgres

  authentication-service:
    image: eann1s/authentication-service:latest
    hostname: authentication-service
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8089:8089
    environment:
      SERVER_PORT: 8089
      DATABASE_URL: postgres:5431
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_URL: kafka:29092
      DISCOVERY_SERVER_URL: discovery-server:8761
      CONFIG_SERVER_URL: config-server:8888

  postgres-authentication-service:
    image: postgres:alpine3.17
    hostname: postgres
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 5431:5432
    environment:
      POSTGRES_DB: authentication-service
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - authentication-service-data:/data/postgres

  redis:
    image: redis:7.2-rc-alpine3.18
    hostname: redis
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 6379:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  discovery-server:
    image: eann1s/discovery-server:latest
    hostname: discovery-server
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8761:8761

  config-server:
    image: eann1s/cloud-config-server:latest
    hostname: config-server
    restart: unless-stopped
    pull_policy: missing
    environment:
      - "CONFIG_LOCATION=https://github.com/Eann1S/config-repo"

volumes:
  heal-order-hub-data: {}
  authentication-service-data: {}
