server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: heal-order-hub
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/heal-order-hub
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: authentication-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    retry:
      topic:
        enabled: true

kafka:
  topics:
    user-register-topic: user-regiser-topic
