server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: heal-order-hub
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/heal-order-hub
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
